// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCd7-aHw5QZsTXv-mndUj0FrpsbiLy1JO8',
    appId: '1:378472914103:web:b26145d405684742768132',
    messagingSenderId: '378472914103',
    projectId: 'todoapp-1d258',
    authDomain: 'todoapp-1d258.firebaseapp.com',
    storageBucket: 'todoapp-1d258.appspot.com',
    measurementId: 'G-3QJSDWZ3DK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChgn0jcpIsCJAe-2iuYEAZ7caxgT7Z8j4',
    appId: '1:378472914103:android:ab64cbb4931e9f44768132',
    messagingSenderId: '378472914103',
    projectId: 'todoapp-1d258',
    storageBucket: 'todoapp-1d258.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaOG-EBxL8XQbO0I9_N9UpILmT972l5sI',
    appId: '1:378472914103:ios:4ddc1756fc20cbf9768132',
    messagingSenderId: '378472914103',
    projectId: 'todoapp-1d258',
    storageBucket: 'todoapp-1d258.appspot.com',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaOG-EBxL8XQbO0I9_N9UpILmT972l5sI',
    appId: '1:378472914103:ios:4ddc1756fc20cbf9768132',
    messagingSenderId: '378472914103',
    projectId: 'todoapp-1d258',
    storageBucket: 'todoapp-1d258.appspot.com',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCd7-aHw5QZsTXv-mndUj0FrpsbiLy1JO8',
    appId: '1:378472914103:web:e28c51822fc9cf19768132',
    messagingSenderId: '378472914103',
    projectId: 'todoapp-1d258',
    authDomain: 'todoapp-1d258.firebaseapp.com',
    storageBucket: 'todoapp-1d258.appspot.com',
    measurementId: 'G-BDM0CXY1ZE',
  );
}
